server:
  port: 10381
logging:
  level:
    com.sinosdx.repair.dal.mapper: debug
spring:
  datasource:
    url: jdbc:mysql://118.89.165.94:3306/repair_server?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        config:
          enabled: true
        commons-log:
          enabled: true
        slf4j:
          enabled: true
        stat:
          enabled: true
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 10000
        wall:
          enabled: true
      initial-size: 3
      max-active: 30
      max-open-prepared-statements: 30
      max-wait: 12000
      min-evictable-idle-time-millis: 30000
      min-idle: 3
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 1 from dual
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        profile-enable: true
        session-stat-enable: true
        url-pattern: /*
    username: root
    password: Meeting#12345

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml


